hand:
  max_width: 0.06

grasp_detection:
  threshold: 0.90

simulation:
  urdf_root: /Users/michel/Data/urdf_zoo

# Warning: only change the values below if you want to generate a new dataset 
# and/or train the network with different parameters

data_generation:  
  n_scenes: 1000
  tsdf_res: 80
  n_viewpoints: 16
  n_grasps: 30

scene:
  rel_size: 4  # times the max opening width of the gripper

network:
  vol_res: 40
